### ISSUE TITLE
Error : Must be return a type of Subscription

### ISSUE THREAD

**Issue by KarlZero974** [rawatsandeep670/ng-auto-cancelable#2]
Hi, I try this package in ionic angular project, and got this error : 'function' must be return a type of Subscription. My fetch function return like demo code, with httpClient

**Comment by rawatsandeep670** [comment]
@OcB974 Can you send me your code snippets ? I think you forgot to return the subscription from your function like below:

`@ngAutoCancelable(true, 1000)
  getData() {
    return this.httpClient
      .get('https://api.spotify.com/v1/albums')
      .subscribe((res: any) => {
        console.log(res);
      });
  }`
If you not return the subscription from **getData** function you will get the same error.
